language: node_js
node_js:
- lts/*
deploy:
  provider: heroku
  api_key:
    secure: CuTlYI1SH5/5GeqwFq5QIf+bQgSuvDrvU4yZPB79J9NuKSct9tsMXvUE15iBnSJPJXQprSr2YC8gFtUlLECitG/G1AzmnhvI4EFO1MPIxhx6SVa2AZ5i9L8DsNo3VULuFLpAaSZRzD58iKkQ5bmP7MDiJNzQCsLj+mg1KcxO11WpoeP10d0nt7MYRyyrvTuusJL0uYwDb68GJfHfxgE0jUBsi3YlUjgVWmFARAIY5p87JtsUcdh0jucyFQ81tcBlF+9GtEGQIYihB9qP+a4WcsLwhklwlno5jaULYvnoXNKwBvX9ivjAe2GGqmp7+gVJxaid3RqsEqBH4NloDRt8L7ipJyYsaITS2qXUbzelQ/Ms6LhE331vpW4xiwe6Q1CKQAwcpdXfjNyajJY4wWtNyE+QSGnOFoLiXAdAaHS/Ubl3LDVnvXqCz1nxAIESEGilVduEc9Nd8O8qAaOx5IoDyI/Nn0v2hnOqzrtGUcKu5YdzQXO72PJETAp33+Op8ii/D7v6DBSCQC73/yFkg/TAhhCV3MiveayG8RQEvU6fw3XpMufW2pkh4p+oVy0eYRpm9l+y5j9k4AMZs4zjteXN09iPdmd0hJS8ZI37eYLdF55JYrm66Fq5mhBthggL921V7UqXy6tVC5HmIYXQuIOvneg75EDJfBL/hgEZK6zbWzI=
  app: twitter-clone-web-app